FROM node:20-alpine
WORKDIR /app
COPY package.json yarn.lock* ./
RUN corepack enable && corepack yarn@stable install --production
COPY . .
EXPOSE 5004
ENV NODE_ENV=production
CMD ["node", "index.js"]
