#!/bin/bash
# Instructions for setting up environment variables

echo "🚀 Setting up AI Component Generator..."
echo ""
echo "1️⃣  GET YOUR FREE GROQ API KEY"
echo "   Visit: https://console.groq.com"
echo "   - Click 'Sign Up'"
echo "   - Create account (email verification)"
echo "   - Go to API Keys section"
echo "   - Click 'Create New API Key'"
echo "   - Copy the key"
echo ""
echo "2️⃣  CREATE .env.local FILE"
echo "   In: frontend/ui-component-library/.env.local"
echo ""
echo "   Add this content:"
echo "   ================================================"
echo "   GROQ_API_KEY=your_actual_api_key_here"
echo "   NEXT_PUBLIC_BACKEND_URL=http://localhost:5004"
echo "   ================================================"
echo ""
echo "3️⃣  RESTART DEV SERVER"
echo "   $ npm run dev"
echo ""
echo "4️⃣  VISIT"
echo "   http://localhost:3000/generative-ai"
echo ""
echo "✅ Done! Start generating components 🎉"
