export const components = [
  { id: "button", label: "Button", href: "/preview/button" },
  { id: "card", label: "Card", href: "/preview/card" },
  { id: "navbar", label: "Navbar", href: "/preview/navbar" },
  { id: "dialog", label: "Dialog", href: "/preview/dialog" },
  { id: "carousel", label: "Carousel", href: "/preview/carousel" },
  { id: "dropdown", label: "Dropdown", href: "/preview/dropdown" },
  { id: "tabs", label: "Tabs", href: "/preview/tabs" },
  { id: "progress", label: "Progress", href: "/preview/progress" },
  { id: "pagination", label: "Pagination", href: "/preview/pagination" },
  { id: "input", label: "Input", href: "/preview/input" },
];

export const Arrayfeaturesection = [
  {
    icon: "⚡",
    title: "Lightning Fast",
    desc: "Generate components in seconds",
  },
  {
    icon: "🎨",
    title: "Production Ready",
    desc: "Clean, optimized React code",
  },
  {
    icon: "📱",
    title: "Responsive Design",
    desc: "Works on all devices",
  },
  {
    icon: "🔧",
    title: "Customizable",
    desc: "Easy to modify and extend",
  },
];

export const Infosecarray = [
  {
    num: "1",
    title: "Write Prompt",
    desc: "Describe what you want to create in natural language",
    icon: "✍️",
  },
  {
    num: "2",
    title: "AI Generates",
    desc: "Our AI creates production-ready React components instantly",
    icon: "⚙️",
  },
  {
    num: "3",
    title: "Copy & Use",
    desc: "Preview, copy code, or download directly to your project",
    icon: "📦",
  },
];

export const styles: any = {
  container: {
    display: "grid",
    gridTemplateColumns: "250px 1fr 300px",
    height: "100vh",
    fontFamily: "Inter, sans-serif",
    background: "#111",
    color: "white",
    overflow: "hidden",
  },
  sidebar: {
    background: "#1a1a1a",
    borderRight: "1px solid #333",
    overflowY: "auto",
  },
  sidebarHeader: { padding: "20px", borderBottom: "1px solid #333" },
  logo: { fontSize: "18px", fontWeight: "800", letterSpacing: "1px" },
  category: { padding: "16px", borderBottom: "1px solid #222" },
  categoryTitle: {
    fontSize: "11px",
    color: "#666",
    textTransform: "uppercase",
    fontWeight: "700",
    marginBottom: "12px",
  },
  componentItem: {
    background: "#2a2a2a",
    padding: "12px",
    borderRadius: "6px",
    marginBottom: "8px",
    cursor: "grab",
    fontSize: "13px",
    border: "1px solid #333",
    display: "flex",
    alignItems: "center",
  },
  canvasWrapper: {
    display: "flex",
    flexDirection: "column",
    background: "white",
  },
  toolbar: {
    padding: "10px 20px",
    borderBottom: "1px solid #333",
    background: "#111",
    display: "flex",
    justifyContent: "flex-end",
  },
  toolbarBtn: {
    background: "#333",
    color: "white",
    border: "none",
    padding: "6px 12px",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  canvas: {
    margin: "40px",
    flex: 1,
    padding: "40px",
    overflowY: "auto",
    position: "relative",
    color: "white",
    borderRadius: "20px",
    background: "black",
  },
  codePanel: {
    background: "#1a1a1a",
    borderLeft: "1px solid #333",
    display: "flex",
    flexDirection: "column",
  },
  panelTabs: {
    padding: "16px",
    borderBottom: "1px solid #333",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  panelTabTitle: { fontSize: "12px", fontWeight: "700" },
  copyBtn: {
    background: "#007AFF",
    border: "none",
    color: "white",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "10px",
    cursor: "pointer",
  },
  panelContent: { flex: 1, overflowY: "auto", padding: "16px" },
  editForm: {
    marginBottom: "32px",
    background: "#222",
    padding: "16px",
    borderRadius: "8px",
  },
  currLabel: {
    display: "block",
    fontSize: "11px",
    color: "#888",
    marginBottom: "4px",
    textTransform: "uppercase",
  },
  inputField: {
    width: "100%",
    background: "#111",
    border: "1px solid #333",
    color: "white",
    padding: "8px",
    borderRadius: "4px",
    fontSize: "13px",
    marginBottom: "12px",
  },
  colorPicker: {
    width: "100%",
    height: "40px",
    padding: 0,
    border: "none",
    background: "transparent",
    marginBottom: "12px",
  },
  saveBtn: {
    width: "100%",
    background: "#28a745",
    color: "white",
    border: "none",
    padding: "10px",
    borderRadius: "4px",
    fontWeight: "600",
    cursor: "pointer",
  },
  codePreview: {
    background: "#000",
    padding: "16px",
    borderRadius: "8px",
    fontSize: "11px",
    fontFamily: "monospace",
    color: "#0f0",
  },
  codeBlock: { margin: 0, whiteSpace: "pre-wrap" },
};
